server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthenticationFilter
            - RateLimitFilter

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - JwtAuthenticationFilter
            - RateLimitFilter